components:
    schemas:
        Category:
            properties:
                categoryId:
                    format: int64
                    type: integer
                name:
                    type: string
        DocumentSelection:
            oneOf:
                - type: object
                  properties:
                      selectionToAddCategoryIds:
                          items:
                              format: int64
                              type: integer
                          type: array
                      selectionToRemoveCategoryIds:
                          items:
                              format: int64
                              type: integer
                          type: array
                - type: object
                  properties:
                      selectionToAddTagNames:
                          items:
                              type: string
                          type: array
                      selectionToRemoveTagNames:
                          items:
                              type: string
                          type: array
            properties:
                documentIds:
                    items:
                        type: string
                    type: array
                selectionScope:
                    properties:
                        folderId:
                            format: int64
                            type: integer
                        repositoryId:
                            format: int64
                            type: integer
                        selectAll:
                            type: boolean
                    type: object
        GenericError:
            description: https://www.schema.org/GenericError
            properties:
                message:
                    type: string
            type: object
        Keyword:
            properties:
                name:
                    type: string
        MessageSelection:
            properties:
                description:
                    type: string
        Status:
            properties:
                actionInProgress:
                    type: boolean
            type: object
        Vocabulary:
            properties:
                categories:
                    items:
                        $ref: "#/components/schemas/Category"
                    type: array
                multiValued:
                    type: boolean
                name:
                    type: string
                vocabularyId:
                    format: int64
                    type: integer
info:
    description: ""
    title: ""
    version: v1.0
openapi: "3.0.1"
paths:
    "/categories/batch":
        patch:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DocumentSelection"
            responses:
                200:
                    content:
                        {}
                    description: ""
            tags: ["Category"]
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DocumentSelection"
            responses:
                200:
                    content:
                        {}
                    description: ""
            tags: ["Category"]
    "/content-spaces/{content-space-id}/vocabularies/common":
        post:
            parameters:
                - in: path
                  name: content-space-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DocumentSelection"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Vocabulary"
                                type: array
                    description: ""
            tags: ["Vocabulary"]
    "/keywords/batch":
        patch:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DocumentSelection"
            responses:
                200:
                    content:
                        {}
                    description: ""
            tags: ["Keyword"]
        put:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DocumentSelection"
            responses:
                200:
                    content:
                        {}
                    description: ""
            tags: ["Keyword"]
    "/keywords/common":
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DocumentSelection"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                items:
                                    $ref: "#/components/schemas/Keyword"
                                type: array
                    description: ""
            tags: ["Keyword"]
    "/keywords/message-selection":
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DocumentSelection"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/MessageSelection"
                    description: ""
            tags: ["MessageSelection"]
    "/status":
        get:
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/Status"
                    description: ""
            tags: ["Status"]
    "/vocabularies/message-selection":
        post:
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/DocumentSelection"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/MessageSelection"
                    description: ""
            tags: ["MessageSelection"]