components:
  schemas:
    AssetCategoryModel:
      properties:
        categoryId:
          format: int64
          type: integer
        name:
          type: string
    AssetVocabularyModel:
      properties:
        categories:
          items:
            $ref: "#/components/schemas/AssetCategoryModel"
          type: array
        multiValued:
          type: boolean
        name:
          type: string
        vocabularyId:
          format: int64
          type: integer
    BulkActionResponseModel:
      properties:
        description:
          type: string
        status:
          type: string
    BulkAssetEntryActionModel:
      properties:
        folderId:
          format: int64
          type: integer
        repositoryId:
          format: int64
          type: integer
        selectAll:
          type: boolean
        selection:
          items:
            type: string
          type: array
    BulkAssetEntryCommonCategoriesModel:
      properties:
        description:
          type: string
        status:
          type: string
        vocabularies:
          items:
            $ref: "#/components/schemas/AssetVocabularyModel"
          type: array
    BulkAssetEntryCommonTagsModel:
      properties:
        description:
          type: string
        groupIds:
          items:
            format: int64
            type: integer
          type: array
        status:
          type: string
        tagNames:
          items:
            type: string
          type: array
    BulkAssetEntryUpdateCategoriesActionModel:
      properties:
        append:
          type: boolean
        toAddCategoryIds:
          items:
            format: int64
            type: integer
          type: array
        toRemoveCategoryIds:
          items:
            format: int64
            type: integer
          type: array
        folderId:
          format: int64
          type: integer
        repositoryId:
          format: int64
          type: integer
        selectAll:
          type: boolean
        selection:
          items:
            type: string
          type: array
    BulkAssetEntryUpdateTagsActionModel:
      properties:
        append:
          type: boolean
        toAddTagNames:
          items:
            type: string
          type: array
        toRemoveTagNames:
          items:
            type: string
          type: array
        folderId:
          format: int64
          type: integer
        repositoryId:
          format: int64
          type: integer
        selectAll:
          type: boolean
        selection:
          items:
            type: string
          type: array
    BulkStatusModel:
      properties:
        status:
          type: boolean
      type: object
info:
  description: ""
  title: ""
  version: v1.0
openapi: "3.0.1"
paths:
  "/categories/{category-class-name-id}":
    post:
      parameters:
        - in: path
          name: classNameId
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BulkAssetEntryUpdateCategoriesActionModel"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BulkActionResponseModel"
          description: ""
      tags: ["BulkActionResponseModel"]
  "/categories/{category-group-id}/{class-name-id}/common":
    post:
      parameters:
        - in: path
          name: groupId
          required: true
          schema:
            format: int64
            type: integer
        - in: path
          name: classNameId
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BulkAssetEntryActionModel"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BulkAssetEntryCommonCategoriesModel"
          description: ""
      tags: ["BulkActionResponseModel"]
  /status:
    get:
      parameters:
        - in: path
          name: classNameId
          required: true
          schema:
            format: int64
            type: integer
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BulkStatusModel"
          description: ""
      tags: ["BulkStatusModel"]
  "/tags/{tag-class-name-id}":
    post:
      parameters:
        - in: path
          name: classNameId
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BulkAssetEntryUpdateTagsActionModel"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BulkActionResponseModel"
          description: ""
      tags: ["BulkActionResponseModel"]
  "/tags/{tag-group-id}/{class-name-id}/common":
    post:
      parameters:
        - in: path
          name: groupId
          required: true
          schema:
            format: int64
            type: integer
        - in: path
          name: classNameId
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BulkAssetEntryActionModel"
      responses:
        200:
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/BulkAssetEntryCommonTagsModel"
          description: ""
      tags: ["BulkActionResponseModel"]