apiDir: "../bulk-rest-api/src/main/java"
apiPackagePath: "com.liferay.bulk.rest"
application:
    baseURI: "/bulk-rest"
    className: "BulkRestApplication"
    name: "Liferay.BulkRest"
author: "Javier Gamarra"
testDir: "../bulk-rest-test/src/testIntegration/java"