components:
    schemas:
        Category:
            properties:
                categoryId:
                    format: int64
                    type: integer
                name:
                    type: string
        Vocabulary:
            properties:
                categories:
                    items:
                        $ref: "#/components/schemas/Category"
                    type: array
                multiValued:
                    type: boolean
                name:
                    type: string
                vocabularyId:
                    format: int64
                    type: integer
        BulkActionResponse:
            properties:
                description:
                    type: string
                status:
                    type: string
        BulkAssetEntryAction:
            properties:
                folderId:
                    format: int64
                    type: integer
                repositoryId:
                    format: int64
                    type: integer
                selectAll:
                    type: boolean
                selection:
                    items:
                        type: string
                    type: array
        BulkAssetEntryCommonCategories:
            properties:
                description:
                    type: string
                status:
                    type: string
                vocabularies:
                    items:
                        $ref: "#/components/schemas/Vocabulary"
                    type: array
        BulkAssetEntryCommonTags:
            properties:
                description:
                    type: string
                groupIds:
                    items:
                        format: int64
                        type: integer
                    type: array
                status:
                    type: string
                tagNames:
                    items:
                        type: string
                    type: array
        BulkAssetEntryUpdateCategoriesAction:
            properties:
                append:
                    type: boolean
                folderId:
                    format: int64
                    type: integer
                repositoryId:
                    format: int64
                    type: integer
                selectAll:
                    type: boolean
                selection:
                    items:
                        type: string
                    type: array
                toAddCategoryIds:
                    items:
                        format: int64
                        type: integer
                    type: array
                toRemoveCategoryIds:
                    items:
                        format: int64
                        type: integer
                    type: array
        BulkAssetEntryUpdateTagsAction:
            properties:
                append:
                    type: boolean
                folderId:
                    format: int64
                    type: integer
                repositoryId:
                    format: int64
                    type: integer
                selectAll:
                    type: boolean
                selection:
                    items:
                        type: string
                    type: array
                toAddTagNames:
                    items:
                        type: string
                    type: array
                toRemoveTagNames:
                    items:
                        type: string
                    type: array
        BulkStatus:
            properties:
                busy:
                    type: boolean
            type: object
info:
    description: ""
    title: ""
    version: v1.0
openapi: "3.0.1"
paths:
    "/categories/{category-class-name-id}":
        post:
            parameters:
                - in: path
                  name: category-class-name-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/BulkAssetEntryUpdateCategoriesAction"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BulkActionResponse"
                    description: ""
            tags: ["BulkActionResponse"]
    "/categories/{category-group-id}/{category-class-name-id}/common":
        post:
            parameters:
                - in: path
                  name: category-group-id
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: path
                  name: category-class-name-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/BulkAssetEntryAction"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BulkAssetEntryCommonCategories"
                    description: ""
            tags: ["BulkActionResponse"]
    "/tags/{tag-class-name-id}":
        post:
            parameters:
                - in: path
                  name: tag-class-name-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/BulkAssetEntryUpdateTagsAction"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BulkActionResponse"
                    description: ""
            tags: ["BulkActionResponse"]
    "/tags/{tag-group-id}/{tag-class-name-id}/common":
        post:
            parameters:
                - in: path
                  name: tag-group-id
                  required: true
                  schema:
                      format: int64
                      type: integer
                - in: path
                  name: tag-class-name-id
                  required: true
                  schema:
                      format: int64
                      type: integer
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: "#/components/schemas/BulkAssetEntryAction"
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BulkAssetEntryCommonTags"
                    description: ""
            tags: ["BulkActionResponse"]
    /status:
        get:
            parameters:
                - in: query
                  name: param
                  required: false
                  schema:
                      format: int64
                      type: integer
            responses:
                200:
                    content:
                        application/json:
                            schema:
                                $ref: "#/components/schemas/BulkStatus"
                    description: ""
            tags: ["BulkStatus"]